Учебный проект: обратная сторона реальности
htmlacademy-react/1521451-guess-melody-5 pull request #4
Opened 2020-10-07 15:39 UTC by AlexandrRumiantsev

2020-10-07 20:11 UTC, DmitryMarkov requested changes
Есть замечания, которые надо исправить. Кроме того, по ТЗ у пользователя должно быть три попытки ответа, а сейчас их две

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.jsx
> +    if (!question || step >= question.lenght) {
lenght = опечатка. Правильно `length`

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.jsx
> +  questions: PropTypes.array.isRequired,
то же про array

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/question-artist/question-artist.jsx
> +                <div key={answer.artist} className="artist">
артисты могут дублироваться, лучше ввести в объект ключ `id`

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/question-artist/question-artist.jsx
> +    }).isRequired,
шейпы лучше вынести в отдельный файл и импортировать везде, где они используются и передаются

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/question-genre/question-genre.jsx
> +                <div key={`${i}-${answer.src}`} className='track'>
индексы в ключах использовать плохая идея

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/question-genre/question-genre.jsx
> +                        const val = evt.target.checked;
плохое имя переменной - val. Оно не говорит о сущности, которую хранит, к тому же противоречит критерию Б5

2020-10-07 20:11 UTC, DmitryMarkov commented on src/components/question-genre/question-genre.jsx
> +                      onChange={(evt) => {
рекомендую выносить всю логику из шаблона в методы

2020-10-12 18:32 UTC, AlexandrRumiantsev commented
1) Всегда надо уточнять массив чего передается через пропс (arrayOf)
- Пофиксил в компонентах: app.jsx, game-screen.jsx
2) Для именований стилей css-классов лучше вспомнить про БЭМ-нотацию или аналогичный подход.
- поправил на app__svg по методологии БЭМ
3) lenght = опечатка. Правильно length
- Пофиксил
4) Артисты могут дублироваться, лучше ввести в объект ключ id
- Ввел в объекты элемент - ID
5) Шейпы лучше вынести в отдельный файл и импортировать везде, где они используются и передаются
- Вынес все шейпы в отдельный файл, третий шейп questionArtist, комбинация из двух других шейпов
6) Плохое имя переменной - val. Оно не говорит о сущности, которую хранит, к тому же противоречит критерию Б5
- Поменял на - userAnswer тк это выбранный пользователем ответ (ответ может включать внутли себя несколько элементов)
7) Рекомендую выносить всю логику из шаблона в методы
- Убрал логику из шаблона в рендере и разместил внутри компонента в методе сhangeAnswer().

2020-10-12 19:17 UTC, AlexandrRumiantsev commented
1) Создал: const noop = () => {}
2) Во всех файлах с шейпами не хватает последней пустой строки (не спрашивай почему 🙂 , но её нужно добавлять во все файлы, обычно это делает сам линтер)
- Все ошибки линтера пофиксил
3) object тоже не используем, у нас же есть shape!
- Поправил, добавил еще один shapes

2020-10-13 07:57 UTC, DmitryMarkov commented
@AlexandrRumiantsev отлично, отправляй на повторную проверку

2020-10-13 08:07 UTC, DmitryMarkov approved these changes
Задание выполнено, ошибки исправлены

2020-10-13 08:07 UTC, merged