Компонент плеера
htmlacademy-react/1521451-guess-melody-5 pull request #5
Opened 2020-10-19 10:51 UTC by AlexandrRumiantsev

2020-10-19 21:44 UTC, DmitryMarkov requested changes
Не выполнен пункт задания

> Обратите внимание: на экране «Угадай жанр» мелодии не должны воспроизводиться одновременно. Нажатие старт воспроизведения мелодии должен ставить на паузу мелодию, которая воспроизводилась до этого.

2020-10-19 21:44 UTC, DmitryMarkov commented on src/shapes/questionArtist.js
> +      answersArtist
здесь возникает ошибка типов в консоли, так же в GameScreen

![image](https://user-images.githubusercontent.com/9193608/96515037-44cdb800-126d-11eb-9129-1abcab091f83.png)

2020-10-20 07:43 UTC, AlexandrRumiantsev commented
1) Переделал функционал воспроизведения плеера. Теперь при переключении мелодии, другие останавливаются.
2) Пофиксил ошибки с пропсами
ps В GameScreen shape убрал, проверяю просто как массив, об этом говорит лектор в 3 лекции Тайминг: 1.41 questions: PropTypes.array.isRequired

2020-10-21 10:59 UTC, DmitryMarkov approved these changes
Замечания исправлены

2020-10-21 10:59 UTC, DmitryMarkov commented on src/shapes/gameScreen.js
> +  picture: PropTypes.string,
не уверен, что это решение проблемы. Если пропс нежны компоненту и приходят пустые, надо разобраться почему так

2020-10-21 10:59 UTC, merged